### ISSUE TITLE
Downloading mcp files not fully working

### ISSUE THREAD

**Issue by mcenderdragon** [MinecraftForge/Remapper#7]
Most of these errors are because the folders are not created and thus it crashes. 
But I dont know what the DirectoryNotEmptyException means, these folders exist and the are 3 *csv files in there.

Happens with fatjar-1.0.4
Log:
```
Downloading: http://files.minecraftforge.net/maven/de/oceanlabs/mcp/mcp_config/1.13.2/mcp_config-1.13.2.zip
To:          C:\Users\Max\.gradle\caches\minecraft\de\oceanlabs\mcp\mcp_config\1.13.2\mcp_config-1.13.2.zip
java.nio.file.NoSuchFileException: C:\Users\Max\.gradle\caches\minecraft\de\oceanlabs\mcp\mcp_config\1.13.2\mcp_config-1.13.2.zip
        at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(Unknown Source)
        at java.nio.file.spi.FileSystemProvider.newOutputStream(Unknown Source)
        at java.nio.file.Files.newOutputStream(Unknown Source)
        at java.nio.file.Files.copy(Unknown Source)
        at net.minecraftforge.remapper.MappingDownloader.download(MappingDownloader.java:306)
        at net.minecraftforge.remapper.MappingDownloader.lambda$download$1(MappingDownloader.java:269)
        at java.lang.Thread.run(Unknown Source)
Downloading: http://files.minecraftforge.net/maven/de/oceanlabs/mcp/mcp_config/1.13.2/mcp_config-1.13.2.zip
To:          C:\Users\Max\.gradle\caches\minecraft\de\oceanlabs\mcp\mcp_config\1.13.2\mcp_config-1.13.2.zip
Downloading: http://files.minecraftforge.net/maven/de/oceanlabs/mcp/mcp_snapshot_nodoc/20190530-1.13.2/mcp_snapshot_nodoc-20190530-1.13.2.zip
To:          C:\Users\Max\.gradle\caches\minecraft\de\oceanlabs\mcp\mcp_snapshot_nodoc\20190530
java.nio.file.DirectoryNotEmptyException: C:\Users\Max\.gradle\caches\minecraft\de\oceanlabs\mcp\mcp_snapshot_nodoc\20190530
        at sun.nio.fs.WindowsFileSystemProvider.implDelete(Unknown Source)
        at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(Unknown Source)
        at java.nio.file.Files.deleteIfExists(Unknown Source)
        at java.nio.file.Files.copy(Unknown Source)
        at net.minecraftforge.remapper.MappingDownloader.download(MappingDownloader.java:306)
        at net.minecraftforge.remapper.MappingDownloader.lambda$download$1(MappingDownloader.java:291)
        at java.lang.Thread.run(Unknown Source)
Downloading: http://files.minecraftforge.net/maven/de/oceanlabs/mcp/mcp_snapshot_nodoc/20190530-1.13.2/mcp_snapshot_nodoc-20190530-1.13.2.zip
To:          C:\Users\Max\.gradle\caches\minecraft\de\oceanlabs\mcp\mcp_snapshot_nodoc\20190530
java.nio.file.DirectoryNotEmptyException: C:\Users\Max\.gradle\caches\minecraft\de\oceanlabs\mcp\mcp_snapshot_nodoc\20190530
        at sun.nio.fs.WindowsFileSystemProvider.implDelete(Unknown Source)
        at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(Unknown Source)
        at java.nio.file.Files.deleteIfExists(Unknown Source)
        at java.nio.file.Files.copy(Unknown Source)
        at net.minecraftforge.remapper.MappingDownloader.download(MappingDownloader.java:306)
        at net.minecraftforge.remapper.MappingDownloader.lambda$download$1(MappingDownloader.java:291)
        at java.lang.Thread.run(Unknown Source)
```

**Comment by LexManos** [comment]
https://github.com/MinecraftForge/Remapper/commit/dc2f6114b281786b72f2465156a801050b6ef4b0#diff-65f88249bd0a85e40b5daa76e28ee18fL305
